// eslint.config.js

const js = require('@eslint/js');
const globals = require('globals');

module.exports = [
    // Generated by `sequelize-mig` in its own style (tabs, double quotes) — not
    // hand-maintained, so it is not held to the project's formatting rules.
    { ignores: ['migrations/*_noname.js'] },
    js.configs.recommended,
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'commonjs',
            globals: globals.node
        },
        rules: {
            semi: ['error', 'always'],
            quotes: ['error', 'single', { allowTemplateLiterals: true }],
            indent: ['error', 4],
            'no-unused-vars': 'warn',
            'comma-dangle': ['error', 'never'],
            'no-console': ['error', { allow: ['warn', 'error', 'info'] }]
        }
    }
];