-- Seeding data for STARTUP role
INSERT INTO public.user_profile_field_master (role_id, source_table, field_name, display_name, is_editable, is_required, type, created_at) VALUES
((select id from company_role_master where role_code = 'STARTUP'), 'company', 'company_name', 'Company Name', false, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'company', 'company_email', 'Company Email', false, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'company', 'mobile_number', 'Mobile Number', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'company', 'country_code', 'Country Code', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'first_name', 'First Name', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'last_name', 'Last Name', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'profile_photo', 'Profile Photo', true, false, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'organization_name', 'Organization Name', false, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'short_bio', 'Short Bio', true, false, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'country', 'Country', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'continent', 'Continent', true, false, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'primary_sector', 'Primary Sector', true, true, 'array', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'linkedin_profile_url', 'Linkedin Profile URL', true, false, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'company_website_url', 'Company Website URL', true, false, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'company_email', 'Email', false, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'country_code', 'Country Code', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'mobile_number', 'Mobile Number', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'startup_industry_sector', 'Startup Industry Sector', true, true, 'array', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'funding_stage', 'Funding Stage', true, false, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'funding_currency', 'Funding Currency', true, false, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'funding_ask_amt_min', 'Funding Ask Amount Min', true, true, 'number', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'funding_ask_amt_max', 'Funding Ask Amount Max', true, true, 'number', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'use_of_funds', 'Use of Funds', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'team_size_min', 'Team Size Min', true, false, 'number', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'team_size_max', 'Team Size Max', true, false, 'number', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'incorporation_certificate', 'Incorporation Certificate', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'pitch_deck_certificate', 'Pitch Deck Certificate', true, true, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'business_description', 'Business Description', true, false, 'string', now()),
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'startup_intent', 'Startup Intent', true, true, 'string', now()),
-- Repeatable {name, url} rows. Read-only on My Profile (that page has no repeatable-row
-- editor); it is captured and edited in the registration complete-profile step.
((select id from company_role_master where role_code = 'STARTUP'), 'user', 'founders', 'Founders & LinkedIn', false, true, 'array', now());

-- Seeding data for INVESTOR role
INSERT INTO public.user_profile_field_master (role_id, source_table, field_name, display_name, is_editable, is_required, type, created_at) VALUES
((select id from company_role_master where role_code = 'INVESTOR'), 'company', 'company_name', 'Company Name', false, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'company', 'company_email', 'Company Email', false, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'company', 'mobile_number', 'Mobile Number', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'company', 'country_code', 'Country Code', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'first_name', 'First Name', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'last_name', 'Last Name', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'profile_photo', 'Profile Photo', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'organization_name', 'Organization Name', false, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'short_bio', 'Short Bio', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'country', 'Country', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'continent', 'Continent', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'primary_sector', 'Primary Sector', true, true, 'array', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'linkedin_profile_url', 'Linkedin Profile URL', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'company_website_url', 'Company Website URL', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'company_email', 'Email', false, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'country_code', 'Country Code', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'mobile_number', 'Mobile Number', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'ticket_currency', 'Ticket Currency', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'ticket_size_amt_min', 'Ticket Size Amt Min', true, true, 'number', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'ticket_size_amt_max', 'Ticket Size Amt Max', true, true, 'number', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'investment_thesis', 'Investment Thesis', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'address', 'Registered Office / Residential Address', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'prefrerred_investment_stage', 'Preferred Investment Stage', true, true, 'array', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'stage_focus', 'Stage Focus', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'investor_sector_preference', 'Investor Sector Preference', true, true, 'array', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'geographic_investment_preference', 'Geographic Investment Preference', true, true, 'array', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'geographic_investment_preference_continent', 'Geographic Investment Preference (Continents)', true, false, 'array', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'investor_type', 'Investor Type', true, true, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'investor_portfolio_overview', 'Investor Portfolio Overview', true, false, 'string', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'number_of_investments_to_date', 'Number of Investments to Date', true, false, 'number', now()),
((select id from company_role_master where role_code = 'INVESTOR'), 'user', 'investor_intent', 'Investor Intent', true, true, 'string', now());

-- Seeding data for B2B role
INSERT INTO public.user_profile_field_master (role_id, source_table, field_name, display_name, is_editable, is_required, type, created_at) VALUES
((select id from company_role_master where role_code = 'B2B'), 'company', 'company_name', 'Company Name', false, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'company', 'company_email', 'Company Email', false, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'company', 'gst_number', 'GST Number', false, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'company', 'cin_number', 'CIN Number', false, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'company', 'mobile_number', 'Mobile Number', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'company', 'country_code', 'Country Code', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'first_name', 'First Name', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'last_name', 'Last Name', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'profile_photo', 'Profile Photo', true, false, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'organization_name', 'Organization Name', false, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'short_bio', 'Short Bio', true, false, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'country', 'Country', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'continent', 'Continent', true, false, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'primary_sector', 'Primary Sector', true, true, 'array', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'linkedin_profile_url', 'Linkedin Profile URL', true, false, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'company_website_url', 'Company Website URL', true, false, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'company_email', 'Email', false, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'country_code', 'Country Code', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'mobile_number', 'Mobile Number', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'b2b_sector', 'B2B Sector', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'b2b_sub_sector', 'B2B Sub Sector', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'business_type', 'Business Type', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'b2b_geography_country', 'Geographies (Countries)', true, true, 'array', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'b2b_geography_continent', 'Geographies (Continents)', true, false, 'array', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'address', 'Registered Office / Residential Address', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'revenue_band', 'Revenue Band', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'min_order_quantity', 'Min Order Quantity', true, null, 'number', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'export_rediness', 'Export Readiness', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'industry_vertical', 'Industry Vertical', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'years_in_operation', 'Years in Operation', true, true, 'number', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'operational_capacity_description', 'Operational Capacity Description', true, false, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'products_ervice_Offered', 'Products/Service Offered', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'business_requirements', 'Business Requirements', true, true, 'string', now()),
((select id from company_role_master where role_code = 'B2B'), 'user', 'b2b_intent', 'B2B Intent', true, true, 'string', now());
