INSERT INTO public.role_field_metadata (role_id, lookup, field_name, source_table, display_name, datatype, is_required, is_encrypted, display_order, is_active, is_registration_field, is_kyc_field, allowed_values, regex_pattern, created_by, created_at, updated_at, is_deleted) VALUES
    ((SELECT id FROM public.company_role_master WHERE role_code = 'STARTUP'), 'incorporation_certificate', 'incorporation_certificate', 'user', 'Incorporation Certificate', 'file', TRUE, TRUE, 1, TRUE, TRUE, TRUE, NULL, NULL, '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
    ((SELECT id FROM public.company_role_master WHERE role_code = 'STARTUP'), 'pitch_deck', 'pitch_deck_certificate', 'user', 'Pitch Deck', 'file', FALSE, FALSE, 1, TRUE, TRUE, FALSE, NULL, NULL, '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
    ((SELECT id FROM public.company_role_master WHERE role_code = 'STARTUP'), 'funding_stage', 'funding_stage', 'user', 'Funding Stage', 'string', TRUE, FALSE, 1, TRUE, TRUE, FALSE, '["Idea","Seed","Series A","Series B","Growth"]'::json, NULL, '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
    ((SELECT id FROM public.company_role_master WHERE role_code = 'INVESTOR'), 'investor_type', 'investor_type', 'user', 'Investor Type', 'string', TRUE, FALSE, 1, TRUE, TRUE, FALSE, '["Angel","VC","Family Office","Corporate VC"]'::json, NULL, '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
    ((SELECT id FROM public.company_role_master WHERE role_code = 'INVESTOR'), 'ticket_size', 'ticket_size_amt_min', 'user', 'Minimum Ticket Size', 'float', TRUE, FALSE, 1, TRUE, TRUE, FALSE, NULL, NULL, '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
    ((SELECT id FROM public.company_role_master WHERE role_code = 'INVESTOR'), 'pan_card', 'document_number', 'user', 'PAN Card', 'file', TRUE, TRUE, 1, TRUE, TRUE, TRUE, NULL, NULL, '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
    ((SELECT id FROM public.company_role_master WHERE role_code = 'B2B'), 'gst_number', 'gst_number', 'user', 'GST Number', 'string', TRUE, TRUE, 1, TRUE, TRUE, TRUE, NULL, '^[0-9A-Z]{15}$', '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
    ((SELECT id FROM public.company_role_master WHERE role_code = 'B2B'), 'cin_number', 'cin_number', 'user', 'CIN Number', 'string', FALSE, TRUE, 1, TRUE, TRUE, TRUE, NULL, NULL, '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE),
    ((SELECT id FROM public.company_role_master WHERE role_code = 'B2B'), 'moq', 'min_order_quantity', 'user', 'Minimum Order Quantity', 'integer', TRUE, FALSE, 1, TRUE, TRUE, FALSE, NULL, NULL, '1147afd6-facc-4ad7-ad73-259cf0fdb347', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE);
