name: Deploy Backend UAT

on:
  push:
    branches:
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          port: 22

          script: |
            export PATH="/home/azureuser/.nvm/versions/node/v22.22.3/bin:$PATH"

            cd /home/azureuser/Bridge-Server

            git pull origin uat

            npm ci

            pm2 restart backend